services:
  - type: web
    name: news-pipeline
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SCHEDULER_INTERVAL
        value: 30
      - key: OUTPUT_DIR
        value: outputs
      - key: STRAPI_API_URL
        value: https://prediction-markets-api-gnuw.onrender.com
      - key: PORT
        value: 10000
    autoDeploy: true
